server:
  port: 1001
spring:
  profiles: server-1
eureka:
  instance:
    hostname: server-1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}
      defaultZone: http://server-2:1002/eureka-server

---

  server:
    port: 1002
  spring:
    profiles: server-2
  eureka:
    instance:
      hostname: server-2
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        #      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}
        defaultZone: http://server-1:1001/eureka-server