server:
  port: 9099
push:
  android-access-id: 2100308204
  android-secret-key: AH3R5487ADXY
  ios-access-id: 2200308205
  ios-secret-key: I7873LW8ALNQ
  type: 1

spring:
  profiles:
    active:
      - dev